server:
  port: 81

spring:
  application:
    name: microservicecloud-consumer-dept

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7101/eureka/
#      ,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#是否需要从eureka上检索服务
    register-with-eureka: true
    fetch-registry: true
