server:
  port: 81

spring:
  application:
    name: microservicecloud-consumer-dept

eureka:
  client:
    service-url:
      defaultZone: http://eureka7102.com:7101/eureka/http://eureka7102.com:7102/eureka/,http://eureka7103.com:7103/eureka/

  instance:
    instance-id: microservicecloud-consumer-dept81
    prefer-ip-address: true     #访问路径可以显示IP地址