server:
  port: 80
  
#
#feign:
#  hystrix:
#    enabled: true
#
#

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7101.com:7101/eureka/,http://eureka7102.com:7102/eureka/,http://eureka7103.com:7103/eureka/